export const frameworks = [
  { label: 'Alphabet', value: 'Alphabet' },
  { label: 'Microsoft', value: 'Microsoft' },
  { label: 'Apple', value: 'Apple' },
  { label: 'Samsung Electronics', value: 'Samsung Electronics' },
  { label: 'Meta Platforms', value: 'Meta Platforms' },
  { label: 'Tencent Holdings', value: 'Tencent Holdings' },
  { label: 'Nestlé', value: 'Nestlé' },
  { label: 'LVMH Louis Vuitton Moet Hennessy', value: 'LVMH Louis Vuitton Moet Hennessy' },
  { label: 'Sony', value: 'Sony' },
  { label: 'Procter & Gamble', value: 'Procter & Gamble' },
  { label: 'Oracle', value: 'Oracle' },
  { label: 'PepsiCo', value: 'PepsiCo' },
  { label: 'Anheuser-Busch InBev', value: 'Anheuser-Busch InBev' },
  { label: 'Cisco Systems', value: 'Cisco Systems' },
  { label: 'IBM', value: 'IBM' },
  { label: 'Coca-Cola', value: 'Coca-Cola' },
  { label: 'Hon Hai Precision', value: 'Hon Hai Precision' },
  { label: 'Abbott Laboratories', value: 'Abbott Laboratories' },
  { label: 'Unilever', value: 'Unilever' },
  { label: 'Salesforce', value: 'Salesforce' },
  { label: 'Itochu', value: 'Itochu' },
  { label: 'Accenture', value: 'Accenture' },
  { label: 'SAP', value: 'SAP' },
  { label: 'Philip Morris International', value: 'Philip Morris International' },
  { label: "L'Oréal", value: "L'Oréal" },
  { label: 'Dell Technologies', value: 'Dell Technologies' },
  { label: 'British American Tobacco', value: 'British American Tobacco' },
  { label: 'Netflix', value: 'Netflix' },
  { label: 'McKesson', value: 'McKesson' },
  { label: 'HCA Healthcare', value: 'HCA Healthcare' },
  { label: 'Medtronic', value: 'Medtronic' },
  { label: "McDonald's", value: "McDonald's" },
  { label: 'Mondelez International', value: 'Mondelez International' },
  { label: 'Xiaomi', value: 'Xiaomi' },
  { label: 'Danaher', value: 'Danaher' },
  { label: 'Kroger', value: 'Kroger' },
  { label: 'EssilorLuxottica', value: 'EssilorLuxottica' },
  { label: 'Kweichow Moutai', value: 'Kweichow Moutai' },
  { label: 'Nike', value: 'Nike' },
  { label: 'Automatic Data Processing', value: 'Automatic Data Processing' },
  { label: 'Cencora', value: 'Cencora' },
  { label: 'Marubeni', value: 'Marubeni' },
  { label: 'Kraft Heinz Company', value: 'Kraft Heinz Company' },
  { label: 'Altria Group', value: 'Altria Group' },
  { label: 'Royal Ahold Delhaize N.V.', value: 'Royal Ahold Delhaize N.V.' },
  { label: 'Stryker', value: 'Stryker' },
  { label: 'Starbucks', value: 'Starbucks' },
  { label: 'Adobe', value: 'Adobe' },
  { label: 'Tesco', value: 'Tesco' },
  { label: 'Booking Holdings', value: 'Booking Holdings' },
  { label: 'Diageo', value: 'Diageo' },
  { label: 'Seven & I Holdings', value: 'Seven & I Holdings' },
  { label: 'Danone', value: 'Danone' },
  { label: 'Cardinal Health', value: 'Cardinal Health' },
  { label: 'Hewlett Packard Enterprise', value: 'Hewlett Packard Enterprise' },
  { label: 'Archer Daniels Midland', value: 'Archer Daniels Midland' },
  { label: 'Becton Dickinson', value: 'Becton Dickinson' },
  { label: 'Intuit', value: 'Intuit' },
  { label: 'Baidu', value: 'Baidu' },
  { label: 'Boston Scientific', value: 'Boston Scientific' },
  { label: 'Tata Consultancy Services', value: 'Tata Consultancy Services' },
  { label: 'HP', value: 'HP' },
  { label: 'Hermès International', value: 'Hermès International' },
  { label: 'Emerson Electric', value: 'Emerson Electric' },
  { label: 'Femsa', value: 'Femsa' },
  { label: 'Imperial Brands', value: 'Imperial Brands' },
  { label: 'Parker-Hannifin', value: 'Parker-Hannifin' },
  { label: 'Royal Caribbean Group', value: 'Royal Caribbean Group' },
  { label: 'Sysco', value: 'Sysco' },
  { label: 'Marriott International', value: 'Marriott International' },
  { label: 'London Stock Exchange', value: 'London Stock Exchange' },
  { label: 'Luxshare Precision Industry', value: 'Luxshare Precision Industry' },
  { label: 'Japan Tobacco', value: 'Japan Tobacco' },
  { label: 'Carnival Corporation', value: 'Carnival Corporation' },
  { label: 'JBS', value: 'JBS' },
  { label: 'Henkel', value: 'Henkel' },
  { label: 'Keurig Dr Pepper', value: 'Keurig Dr Pepper' },
  { label: 'NetEase', value: 'NetEase' },
  { label: 'Compass Group', value: 'Compass Group' },
  { label: 'Quanta Computer', value: 'Quanta Computer' },
  { label: 'General Mills', value: 'General Mills' },
  { label: 'Amphenol', value: 'Amphenol' },
  { label: 'Muyuan Foodstuff', value: 'Muyuan Foodstuff' },
  { label: 'Coca-Cola Europacific Partners', value: 'Coca-Cola Europacific Partners' },
  { label: 'Wilmar International', value: 'Wilmar International' },
  { label: 'Reckitt Benckiser Group', value: 'Reckitt Benckiser Group' },
  { label: 'GE HealthCare Technologies', value: 'GE HealthCare Technologies' },
  { label: 'Lenovo Group', value: 'Lenovo Group' },
  { label: 'Recruit Holdings', value: 'Recruit Holdings' },
  { label: 'Canon', value: 'Canon' },
  { label: 'Wuliangye Yibin', value: 'Wuliangye Yibin' },
  { label: 'Infosys', value: 'Infosys' },
  { label: 'Tyson Foods', value: 'Tyson Foods' },
  { label: 'Colgate-Palmolive', value: 'Colgate-Palmolive' },
  { label: 'George Weston', value: 'George Weston' },
  { label: 'Naspers', value: 'Naspers' },
  { label: 'Fujifilm Holdings', value: 'Fujifilm Holdings' },
  { label: 'Capgemini', value: 'Capgemini' },
  { label: 'Kering', value: 'Kering' },
  { label: 'Fujitsu', value: 'Fujitsu' },
  { label: 'Corteva', value: 'Corteva' },
  { label: 'Cognizant', value: 'Cognizant' },
  { label: 'Associated British Foods', value: 'Associated British Foods' },
  { label: 'NEC', value: 'NEC' },
  { label: 'BOE Technology Group', value: 'BOE Technology Group' },
  { label: 'Aeon', value: 'Aeon' },
  { label: 'Kimberly-Clark', value: 'Kimberly-Clark' },
  { label: 'ServiceNow', value: 'ServiceNow' },
  { label: 'Nokia', value: 'Nokia' },
  { label: 'Asahi Group Holdings', value: 'Asahi Group Holdings' },
  { label: 'Woolworths', value: 'Woolworths' },
  { label: 'Pernod Ricard', value: 'Pernod Ricard' },
  { label: 'Kenvue', value: 'Kenvue' },
  { label: 'Intuitive Surgical', value: 'Intuitive Surgical' },
  { label: 'Adidas', value: 'Adidas' },
  { label: 'Heineken', value: 'Heineken' },
  { label: 'Tenet Healthcare', value: 'Tenet Healthcare' },
  { label: 'Albertsons', value: 'Albertsons' },
  { label: 'KLA', value: 'KLA' },
  { label: 'Inner Mongolia Yili', value: 'Inner Mongolia Yili' },
  { label: 'Nintendo', value: 'Nintendo' },
  { label: 'Keyence', value: 'Keyence' },
  { label: 'Spotify Technology', value: 'Spotify Technology' },
  { label: 'Fresenius', value: 'Fresenius' },
  { label: 'Roper Technologies', value: 'Roper Technologies' },
  { label: 'Alcon', value: 'Alcon' },
  { label: 'Sinopharm Group', value: 'Sinopharm Group' },
  { label: 'HCLTech', value: 'HCLTech' },
  { label: 'Palo Alto Networks', value: 'Palo Alto Networks' },
  { label: 'Hikvision', value: 'Hikvision' },
  { label: 'Bunge Global', value: 'Bunge Global' },
  { label: 'East Money Information', value: 'East Money Information' },
  { label: 'Fidelity National Information (FIS)', value: 'Fidelity National Information (FIS)' },
  { label: 'Western Digital', value: 'Western Digital' },
  { label: 'Thomson Reuters', value: 'Thomson Reuters' },
  { label: 'Hilton Worldwide Holdings', value: 'Hilton Worldwide Holdings' },
  { label: 'ZTE', value: 'ZTE' },
  { label: 'Shopify', value: 'Shopify' },
  { label: 'Chipotle Mexican Grill', value: 'Chipotle Mexican Grill' },
  { label: 'Motorola Solutions', value: 'Motorola Solutions' },
  { label: 'TDK', value: 'TDK' },
  { label: 'ITC', value: 'ITC' },
  { label: 'Murata Manufacturing', value: 'Murata Manufacturing' },
  { label: 'WH Group', value: 'WH Group' },
  { label: 'Super Micro Computer', value: 'Super Micro Computer' },
  { label: 'Las Vegas Sands', value: 'Las Vegas Sands' },
  { label: 'CP All', value: 'CP All' },
  { label: 'The Hershey Company', value: 'The Hershey Company' },
  { label: 'Arista Networks', value: 'Arista Networks' },
  { label: 'Anta Sports Products', value: 'Anta Sports Products' },
  { label: 'Kellanova', value: 'Kellanova' },
  { label: 'CDW', value: 'CDW' },
  { label: 'Flex', value: 'Flex' },
  { label: 'Lululemon Athletica', value: 'Lululemon Athletica' },
  { label: 'Corning', value: 'Corning' },
  { label: 'Ericsson', value: 'Ericsson' },
  { label: 'Delta Electronics', value: 'Delta Electronics' },
  { label: 'Naver', value: 'Naver' },
  { label: 'Wipro', value: 'Wipro' },
  { label: 'Essity', value: 'Essity' },
  { label: 'Leidos', value: 'Leidos' },
  { label: 'Legrand', value: 'Legrand' },
  { label: 'Philips', value: 'Philips' },
  { label: 'Grupo Bimbo', value: 'Grupo Bimbo' },
  { label: 'Monster Beverage', value: 'Monster Beverage' },
  { label: 'Restaurant Brands International', value: 'Restaurant Brands International' },
  { label: 'MGM Resorts', value: 'MGM Resorts' },
  { label: "Wen's Foodstuff Group", value: "Wen's Foodstuff Group" },
  { label: 'Costco Wholesale', value: 'Costco Wholesale' },
]
