# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: ss2d22@soton.ac.uk
author_name: sriram
contract_name: tradeflow
preset_name: production
project_name: tradeflow-contracts

