'use client'

import * as React from 'react'
import { CheckIcon, ChevronsUpDownIcon } from 'lucide-react'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'

const frameworks = [
  { label: 'Alphabet', value: 'Alphabet' },
  { label: 'Microsoft', value: 'Microsoft' },
  { label: 'Apple', value: 'Apple' },
  { label: 'Samsung Electronics', value: 'Samsung Electronics' },
  { label: 'Meta Platforms', value: 'Meta Platforms' },
  { label: 'Tencent Holdings', value: 'Tencent Holdings' },
  { label: 'Nestlé', value: 'Nestlé' },
  { label: 'LVMH Louis Vuitton Moet Hennessy', value: 'LVMH Louis Vuitton Moet Hennessy' },
  { label: 'Sony', value: 'Sony' },
  { label: 'Procter & Gamble', value: 'Procter & Gamble' },
  { label: 'Oracle', value: 'Oracle' },
  { label: 'PepsiCo', value: 'PepsiCo' },
  { label: 'Anheuser-Busch InBev', value: 'Anheuser-Busch InBev' },
  { label: 'Cisco Systems', value: 'Cisco Systems' },
  { label: 'IBM', value: 'IBM' },
  { label: 'Coca-Cola', value: 'Coca-Cola' },
  { label: 'Hon Hai Precision', value: 'Hon Hai Precision' },
  { label: 'Abbott Laboratories', value: 'Abbott Laboratories' },
  { label: 'Unilever', value: 'Unilever' },
  { label: 'Salesforce', value: 'Salesforce' },
  { label: 'Itochu', value: 'Itochu' },
  { label: 'Accenture', value: 'Accenture' },
  { label: 'SAP', value: 'SAP' },
  { label: 'Philip Morris International', value: 'Philip Morris International' },
  { label: "L'Oréal", value: "L'Oréal" },
  { label: 'Dell Technologies', value: 'Dell Technologies' },
  { label: 'British American Tobacco', value: 'British American Tobacco' },
  { label: 'Netflix', value: 'Netflix' },
  { label: 'McKesson', value: 'McKesson' },
  { label: 'HCA Healthcare', value: 'HCA Healthcare' },
  { label: 'Medtronic', value: 'Medtronic' },
  { label: "McDonald's", value: "McDonald's" },
  { label: 'Mondelez International', value: 'Mondelez International' },
  { label: 'Xiaomi', value: 'Xiaomi' },
  { label: 'Danaher', value: 'Danaher' },
  { label: 'Kroger', value: 'Kroger' },
  { label: 'EssilorLuxottica', value: 'EssilorLuxottica' },
  { label: 'Kweichow Moutai', value: 'Kweichow Moutai' },
  { label: 'Nike', value: 'Nike' },
  { label: 'Automatic Data Processing', value: 'Automatic Data Processing' },
  { label: 'Cencora', value: 'Cencora' },
  { label: 'Marubeni', value: 'Marubeni' },
  { label: 'Kraft Heinz Company', value: 'Kraft Heinz Company' },
  { label: 'Altria Group', value: 'Altria Group' },
  { label: 'Royal Ahold Delhaize N.V.', value: 'Royal Ahold Delhaize N.V.' },
  { label: 'Stryker', value: 'Stryker' },
  { label: 'Starbucks', value: 'Starbucks' },
  { label: 'Adobe', value: 'Adobe' },
  { label: 'Tesco', value: 'Tesco' },
  { label: 'Booking Holdings', value: 'Booking Holdings' },
  { label: 'Diageo', value: 'Diageo' },
  { label: 'Seven & I Holdings', value: 'Seven & I Holdings' },
  { label: 'Danone', value: 'Danone' },
  { label: 'Cardinal Health', value: 'Cardinal Health' },
  { label: 'Hewlett Packard Enterprise', value: 'Hewlett Packard Enterprise' },
  { label: 'Archer Daniels Midland', value: 'Archer Daniels Midland' },
  { label: 'Becton Dickinson', value: 'Becton Dickinson' },
  { label: 'Intuit', value: 'Intuit' },
  { label: 'Baidu', value: 'Baidu' },
  { label: 'Boston Scientific', value: 'Boston Scientific' },
  { label: 'Tata Consultancy Services', value: 'Tata Consultancy Services' },
  { label: 'HP', value: 'HP' },
  { label: 'Hermès International', value: 'Hermès International' },
  { label: 'Emerson Electric', value: 'Emerson Electric' },
  { label: 'Femsa', value: 'Femsa' },
  { label: 'Imperial Brands', value: 'Imperial Brands' },
  { label: 'Parker-Hannifin', value: 'Parker-Hannifin' },
  { label: 'Royal Caribbean Group', value: 'Royal Caribbean Group' },
  { label: 'Sysco', value: 'Sysco' },
  { label: 'Marriott International', value: 'Marriott International' },
  { label: 'London Stock Exchange', value: 'London Stock Exchange' },
  { label: 'Luxshare Precision Industry', value: 'Luxshare Precision Industry' },
  { label: 'Japan Tobacco', value: 'Japan Tobacco' },
  { label: 'Carnival Corporation', value: 'Carnival Corporation' },
  { label: 'JBS', value: 'JBS' },
  { label: 'Henkel', value: 'Henkel' },
  { label: 'Keurig Dr Pepper', value: 'Keurig Dr Pepper' },
  { label: 'NetEase', value: 'NetEase' },
  { label: 'Compass Group', value: 'Compass Group' },
  { label: 'Quanta Computer', value: 'Quanta Computer' },
  { label: 'General Mills', value: 'General Mills' },
  { label: 'Amphenol', value: 'Amphenol' },
  { label: 'Muyuan Foodstuff', value: 'Muyuan Foodstuff' },
  { label: 'Coca-Cola Europacific Partners', value: 'Coca-Cola Europacific Partners' },
  { label: 'Wilmar International', value: 'Wilmar International' },
  { label: 'Reckitt Benckiser Group', value: 'Reckitt Benckiser Group' },
  { label: 'GE HealthCare Technologies', value: 'GE HealthCare Technologies' },
  { label: 'Lenovo Group', value: 'Lenovo Group' },
  { label: 'Recruit Holdings', value: 'Recruit Holdings' },
  { label: 'Canon', value: 'Canon' },
  { label: 'Wuliangye Yibin', value: 'Wuliangye Yibin' },
  { label: 'Infosys', value: 'Infosys' },
  { label: 'Tyson Foods', value: 'Tyson Foods' },
  { label: 'Colgate-Palmolive', value: 'Colgate-Palmolive' },
  { label: 'George Weston', value: 'George Weston' },
  { label: 'Naspers', value: 'Naspers' },
  { label: 'Fujifilm Holdings', value: 'Fujifilm Holdings' },
  { label: 'Capgemini', value: 'Capgemini' },
  { label: 'Kering', value: 'Kering' },
  { label: 'Fujitsu', value: 'Fujitsu' },
  { label: 'Corteva', value: 'Corteva' },
  { label: 'Cognizant', value: 'Cognizant' },
  { label: 'Associated British Foods', value: 'Associated British Foods' },
  { label: 'NEC', value: 'NEC' },
  { label: 'BOE Technology Group', value: 'BOE Technology Group' },
  { label: 'Aeon', value: 'Aeon' },
  { label: 'Kimberly-Clark', value: 'Kimberly-Clark' },
  { label: 'ServiceNow', value: 'ServiceNow' },
  { label: 'Nokia', value: 'Nokia' },
  { label: 'Asahi Group Holdings', value: 'Asahi Group Holdings' },
  { label: 'Woolworths', value: 'Woolworths' },
  { label: 'Pernod Ricard', value: 'Pernod Ricard' },
  { label: 'Kenvue', value: 'Kenvue' },
  { label: 'Intuitive Surgical', value: 'Intuitive Surgical' },
  { label: 'Adidas', value: 'Adidas' },
  { label: 'Heineken', value: 'Heineken' },
  { label: 'Tenet Healthcare', value: 'Tenet Healthcare' },
  { label: 'Albertsons', value: 'Albertsons' },
  { label: 'KLA', value: 'KLA' },
  { label: 'Inner Mongolia Yili', value: 'Inner Mongolia Yili' },
  { label: 'Nintendo', value: 'Nintendo' },
  { label: 'Keyence', value: 'Keyence' },
  { label: 'Spotify Technology', value: 'Spotify Technology' },
  { label: 'Fresenius', value: 'Fresenius' },
  { label: 'Roper Technologies', value: 'Roper Technologies' },
  { label: 'Alcon', value: 'Alcon' },
  { label: 'Sinopharm Group', value: 'Sinopharm Group' },
  { label: 'HCLTech', value: 'HCLTech' },
  { label: 'Palo Alto Networks', value: 'Palo Alto Networks' },
  { label: 'Hikvision', value: 'Hikvision' },
  { label: 'Bunge Global', value: 'Bunge Global' },
  { label: 'East Money Information', value: 'East Money Information' },
  { label: 'Fidelity National Information (FIS)', value: 'Fidelity National Information (FIS)' },
  { label: 'Western Digital', value: 'Western Digital' },
  { label: 'Thomson Reuters', value: 'Thomson Reuters' },
  { label: 'Hilton Worldwide Holdings', value: 'Hilton Worldwide Holdings' },
  { label: 'ZTE', value: 'ZTE' },
  { label: 'Shopify', value: 'Shopify' },
  { label: 'Chipotle Mexican Grill', value: 'Chipotle Mexican Grill' },
  { label: 'Motorola Solutions', value: 'Motorola Solutions' },
  { label: 'TDK', value: 'TDK' },
  { label: 'ITC', value: 'ITC' },
  { label: 'Murata Manufacturing', value: 'Murata Manufacturing' },
  { label: 'WH Group', value: 'WH Group' },
  { label: 'Super Micro Computer', value: 'Super Micro Computer' },
  { label: 'Las Vegas Sands', value: 'Las Vegas Sands' },
  { label: 'CP All', value: 'CP All' },
  { label: 'The Hershey Company', value: 'The Hershey Company' },
  { label: 'Arista Networks', value: 'Arista Networks' },
  { label: 'Anta Sports Products', value: 'Anta Sports Products' },
  { label: 'Kellanova', value: 'Kellanova' },
  { label: 'CDW', value: 'CDW' },
  { label: 'Flex', value: 'Flex' },
  { label: 'Lululemon Athletica', value: 'Lululemon Athletica' },
  { label: 'Corning', value: 'Corning' },
  { label: 'Ericsson', value: 'Ericsson' },
  { label: 'Delta Electronics', value: 'Delta Electronics' },
  { label: 'Naver', value: 'Naver' },
  { label: 'Wipro', value: 'Wipro' },
  { label: 'Essity', value: 'Essity' },
  { label: 'Leidos', value: 'Leidos' },
  { label: 'Legrand', value: 'Legrand' },
  { label: 'Philips', value: 'Philips' },
  { label: 'Grupo Bimbo', value: 'Grupo Bimbo' },
  { label: 'Monster Beverage', value: 'Monster Beverage' },
  { label: 'Restaurant Brands International', value: 'Restaurant Brands International' },
  { label: 'MGM Resorts', value: 'MGM Resorts' },
  { label: "Wen's Foodstuff Group", value: "Wen's Foodstuff Group" },
  { label: 'Coles Group', value: 'Coles Group' },
  { label: 'Flutter Entertainment', value: 'Flutter Entertainment' },
  { label: 'Jeronimo Martins', value: 'Jeronimo Martins' },
  { label: 'Givaudan', value: 'Givaudan' },
  { label: 'Synopsys', value: 'Synopsys' },
  { label: 'Asustek Computer', value: 'Asustek Computer' },
  { label: 'Molson Coors Brewing', value: 'Molson Coors Brewing' },
  { label: 'Dassault Systemes', value: 'Dassault Systemes' },
  { label: 'Uni-President', value: 'Uni-President' },
  { label: 'Yum! Brands', value: 'Yum! Brands' },
  { label: 'CGI', value: 'CGI' },
  { label: 'Constellation Software', value: 'Constellation Software' },
  { label: 'TCL', value: 'TCL' },
  { label: 'Fortinet', value: 'Fortinet' },
  { label: 'AppLovin', value: 'AppLovin' },
  { label: 'Labcorp Holdings', value: 'Labcorp Holdings' },
  { label: 'Beiersdorf', value: 'Beiersdorf' },
  { label: 'Darden Restaurants', value: 'Darden Restaurants' },
  { label: 'Arca Continental', value: 'Arca Continental' },
  { label: 'Swire Pacific', value: 'Swire Pacific' },
  { label: 'DiDi Global', value: 'DiDi Global' },
  { label: 'Nongfu Spring', value: 'Nongfu Spring' },
  { label: 'Zimmer Biomet', value: 'Zimmer Biomet' },
  { label: 'Carlsberg', value: 'Carlsberg' },
  { label: 'Workday', value: 'Workday' },
  { label: 'Electronic Arts', value: 'Electronic Arts' },
  { label: 'Amadeus IT Group', value: 'Amadeus IT Group' },
  { label: 'Garmin', value: 'Garmin' },
  { label: 'Universal Health Services', value: 'Universal Health Services' },
  { label: 'Shenzhen Mindray Bio-Medical Electronics', value: 'Shenzhen Mindray Bio-Medical Electronics' },
  { label: 'Edwards Lifesciences', value: 'Edwards Lifesciences' },
  { label: 'Quest Diagnostics', value: 'Quest Diagnostics' },
  { label: 'Shanxi Xinghuacun Fen Wine Factory', value: 'Shanxi Xinghuacun Fen Wine Factory' },
  { label: 'J Sainsbury', value: 'J Sainsbury' },
  { label: 'Cadence Design', value: 'Cadence Design' },
  { label: 'Coca-Cola HBC', value: 'Coca-Cola HBC' },
  { label: 'Autodesk', value: 'Autodesk' },
  { label: 'Metro', value: 'Metro' },
  { label: 'International Flavors & Fragrances', value: 'International Flavors & Fragrances' },
  { label: 'Hoya', value: 'Hoya' },
  { label: 'US Foods', value: 'US Foods' },
  { label: 'DaVita', value: 'DaVita' },
  { label: 'Agilent Technologies', value: 'Agilent Technologies' },
  { label: 'Yum China Holdings', value: 'Yum China Holdings' },
  { label: 'Luzhou Lao Jiao', value: 'Luzhou Lao Jiao' },
  { label: 'The Estée Lauder Companies', value: 'The Estée Lauder Companies' },
  { label: 'Hexagon', value: 'Hexagon' },
  { label: 'Gartner', value: 'Gartner' },
  { label: 'Constellation Brands', value: 'Constellation Brands' },
  { label: 'ResMed', value: 'ResMed' },
  { label: 'Olam Group', value: 'Olam Group' },
  { label: 'Sodexo', value: 'Sodexo' },
  { label: 'Seagate Technology', value: 'Seagate Technology' },
  { label: 'Vertiv Holdings', value: 'Vertiv Holdings' },
  { label: 'Baxter International', value: 'Baxter International' },
  { label: 'Wistron', value: 'Wistron' },
  { label: 'Hormel Foods', value: 'Hormel Foods' },
  { label: 'MicroStrategy', value: 'MicroStrategy' },
  { label: 'Kao', value: 'Kao' },
  { label: 'CJ Corporation', value: 'CJ Corporation' },
  { label: 'Pegatron', value: 'Pegatron' },
  { label: 'Guangdong Haid Group', value: 'Guangdong Haid Group' },
  { label: "JDE Peet's", value: "JDE Peet's" },
  { label: 'Marfrig Global Foods', value: 'Marfrig Global Foods' },
  { label: 'Advantest', value: 'Advantest' },
  { label: 'Pinterest', value: 'Pinterest' },
  { label: 'Fortive', value: 'Fortive' },
  { label: 'Terumo', value: 'Terumo' },
  { label: 'IDEXX Laboratories', value: 'IDEXX Laboratories' },
  { label: 'SS&C Technologies', value: 'SS&C Technologies' },
  { label: 'Foshan Haitian Flavouring and Food', value: 'Foshan Haitian Flavouring and Food' },
  { label: 'Ajinomoto', value: 'Ajinomoto' },
  { label: 'Broadridge Financial', value: 'Broadridge Financial' },
  { label: 'NetApp', value: 'NetApp' },
  { label: 'Kirin Holdings', value: 'Kirin Holdings' },
  { label: 'Charoen Pokphand Group', value: 'Charoen Pokphand Group' },
  { label: 'Lindt & Sprungli', value: 'Lindt & Sprungli' },
  { label: 'Toray Industries', value: 'Toray Industries' },
  { label: "Rede D'Oro Luiz", value: "Rede D'Oro Luiz" },
  { label: 'Evolution Gaming Group AB', value: 'Evolution Gaming Group AB' },
  { label: 'Zoom Video Communications', value: 'Zoom Video Communications' },
  { label: 'Veeva Systems', value: 'Veeva Systems' },
  { label: 'Tongwei', value: 'Tongwei' },
  { label: 'Aristocrat Leisure', value: 'Aristocrat Leisure' },
  { label: 'Shenzhen Transsion Holding', value: 'Shenzhen Transsion Holding' },
  { label: 'Trimble', value: 'Trimble' },
  { label: 'Palantir Technologies', value: 'Palantir Technologies' },
  { label: 'Ingram Micro Holding', value: 'Ingram Micro Holding' },
  { label: 'Kerry Group', value: 'Kerry Group' },
  { label: 'McCormick', value: 'McCormick' },
  { label: 'VeriSign', value: 'VeriSign' },
  { label: 'Smithfield Foods', value: 'Smithfield Foods' },
  { label: 'Mettler-Toledo International', value: 'Mettler-Toledo International' },
  { label: 'Norwegian Cruise Line Holdings', value: 'Norwegian Cruise Line Holdings' },
  { label: 'Check Point Software', value: 'Check Point Software' },
  { label: 'First Pacific', value: 'First Pacific' },
  { label: 'FICO', value: 'FICO' },
  { label: 'DocuSign', value: 'DocuSign' },
  { label: 'Galaxy Entertainment', value: 'Galaxy Entertainment' },
  { label: 'Thai Beverage', value: 'Thai Beverage' },
  { label: 'Jiangsu Yanghe Brewery', value: 'Jiangsu Yanghe Brewery' },
  { label: 'Conagra Brands', value: 'Conagra Brands' },
  { label: 'Coloplast', value: 'Coloplast' },
  { label: 'LG Display', value: 'LG Display' },
  { label: 'Hyatt Hotels', value: 'Hyatt Hotels' },
  { label: 'Brown-Forman', value: 'Brown-Forman' },
  { label: 'Deckers Outdoor', value: 'Deckers Outdoor' },
  { label: 'CrowdStrike', value: 'CrowdStrike' },
  { label: 'Dr. Sulaiman Al-Habib Medical Services Group', value: 'Dr. Sulaiman Al-Habib Medical Services Group' },
  { label: 'Prada', value: 'Prada' },
  { label: 'Dexcom', value: 'Dexcom' },
  { label: 'Ansys', value: 'Ansys' },
  { label: 'Suntory Beverage & Food', value: 'Suntory Beverage & Food' },
  { label: 'Nitto Denko', value: 'Nitto Denko' },
  { label: 'Empire', value: 'Empire' },
  { label: 'Keysight Technologies', value: 'Keysight Technologies' },
  { label: 'Church & Dwight', value: 'Church & Dwight' },
  { label: 'Savola Group', value: 'Savola Group' },
  { label: 'Caesars Entertainment', value: 'Caesars Entertainment' },
  { label: 'MIXUE Group', value: 'MIXUE Group' },
  { label: 'Ralph Lauren', value: 'Ralph Lauren' },
  { label: 'Atlassian', value: 'Atlassian' },
  { label: 'Campbell Soup', value: 'Campbell Soup' },
  { label: 'Waters', value: 'Waters' },
  { label: 'Nomura Research Institute', value: 'Nomura Research Institute' },
  { label: 'Huaqin Technology', value: 'Huaqin Technology' },
  { label: 'Snowflake', value: 'Snowflake' },
  { label: 'Metro Group', value: 'Metro Group' },
  { label: 'Moncler SpA', value: 'Moncler SpA' },
  { label: 'United Natural Foods', value: 'United Natural Foods' },
  { label: 'Sonova Holding', value: 'Sonova Holding' },
  { label: 'Roblox', value: 'Roblox' },
  { label: 'NEXON', value: 'NEXON' },
  { label: 'JM Smucker', value: 'JM Smucker' },
  { label: 'Krafton', value: 'Krafton' },
  { label: 'Compal Electronics', value: 'Compal Electronics' },
  { label: 'Gen Digital', value: 'Gen Digital' },
  { label: 'Cloudflare', value: 'Cloudflare' },
  { label: 'Tingyi Holding', value: 'Tingyi Holding' },
  { label: 'Take-Two Interactive Software', value: 'Take-Two Interactive Software' },
  { label: 'Barry Callebaut', value: 'Barry Callebaut' },
  { label: 'IEIT Systems', value: 'IEIT Systems' },
  { label: 'Computershare', value: 'Computershare' },
  { label: 'Doosan', value: 'Doosan' },
  { label: 'InterContinental Hotels', value: 'InterContinental Hotels' },
  { label: 'Datadog', value: 'Datadog' },
  { label: 'CoStar Group', value: 'CoStar Group' },
  { label: 'Medipal Holdings', value: 'Medipal Holdings' },
  { label: 'Clorox', value: 'Clorox' },
  { label: 'Unicharm', value: 'Unicharm' },
  { label: 'BIM Birlesik Magazalar', value: 'BIM Birlesik Magazalar' },
  { label: 'Hologic', value: 'Hologic' },
  { label: 'Coca-Cola Bottling Consolidated', value: 'Coca-Cola Bottling Consolidated' },
  { label: 'Aramark', value: 'Aramark' },
  { label: 'Hygon Information Technology', value: 'Hygon Information Technology' },
  { label: 'HubSpot', value: 'HubSpot' },
  { label: "Domino's Pizza", value: "Domino's Pizza" },
  { label: 'Anhui Gujing Distillery', value: 'Anhui Gujing Distillery' },
  { label: 'Jointown Pharmaceutical Group', value: 'Jointown Pharmaceutical Group' },
  { label: 'Goertek', value: 'Goertek' },
  { label: 'CoreWeave', value: 'CoreWeave' },
  { label: 'Eastroc Beverage (Group)', value: 'Eastroc Beverage (Group)' },
  { label: 'F5', value: 'F5' },
  { label: 'Steris', value: 'Steris' },
  { label: 'Almarai', value: 'Almarai' },
  { label: 'ELM', value: 'ELM' },
  { label: 'Sprouts Farmers Markets', value: 'Sprouts Farmers Markets' },
  { label: 'Olympus', value: 'Olympus' },
  { label: 'Inventec', value: 'Inventec' },
  { label: 'Konami', value: 'Konami' },
  { label: 'Trade Desk', value: 'Trade Desk' },
  { label: 'Kesko', value: 'Kesko' },
  { label: 'Tech Mahindra', value: 'Tech Mahindra' },
  { label: 'China Mengniu Dairy', value: 'China Mengniu Dairy' },
  { label: 'Alfresa Holdings', value: 'Alfresa Holdings' },
  { label: 'Hengyi Petrochemical', value: 'Hengyi Petrochemical' },
  { label: 'Shenzhou International Group Holdings', value: 'Shenzhou International Group Holdings' },
  { label: 'Ricoh', value: 'Ricoh' },
  { label: 'Solventum', value: 'Solventum' },
  { label: 'Ag Anadolu Grubu Holding Anonim Sirketi', value: 'Ag Anadolu Grubu Holding Anonim Sirketi' },
  { label: 'CP Axtra', value: 'CP Axtra' },
  { label: 'Digital China Group', value: 'Digital China Group' },
  { label: 'Haidilao International Holding', value: 'Haidilao International Holding' },
  { label: 'Aier Eye Hospital Group', value: 'Aier Eye Hospital Group' },
  { label: 'New Hope Liuhe', value: 'New Hope Liuhe' },
  { label: 'IHH Healthcare', value: 'IHH Healthcare' },
  { label: 'Straumann Holding', value: 'Straumann Holding' },
  { label: 'Celestica', value: 'Celestica' },
  { label: 'Delivery Hero', value: 'Delivery Hero' },
  { label: 'Ubiquiti', value: 'Ubiquiti' },
  { label: 'Bid', value: 'Bid' },
  { label: 'Tyler Technologies', value: 'Tyler Technologies' },
  { label: 'Samsara', value: 'Samsara' },
  { label: 'Skechers USA', value: 'Skechers USA' },
  { label: 'Unisplendour', value: 'Unisplendour' },
  { label: 'AVIC Chengdu Aircraft', value: 'AVIC Chengdu Aircraft' },
  { label: 'China Resources Beer (Holdings)', value: 'China Resources Beer (Holdings)' },
  { label: 'Accor', value: 'Accor' },
  { label: 'Logitech International', value: 'Logitech International' },
  { label: 'Reddit', value: 'Reddit' },
  { label: 'LG Innotek Co.,', value: 'LG Innotek Co.,' },
  { label: 'Jiangxi Zhengbang Technology', value: 'Jiangxi Zhengbang Technology' },
  { label: 'Dino Polska', value: 'Dino Polska' },
  { label: 'Costco Wholesale', value: 'Costco Wholesale' },
]

export function BuyerAddressComboBox() {
  const [open, setOpen] = React.useState(false)
  const [value, setValue] = React.useState('')

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button variant="outline" role="combobox" aria-expanded={open} className="w-full justify-between">
          {value ? frameworks.find((framework) => framework.value === value)?.label : 'Select Buyer address...'}
          <ChevronsUpDownIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-full p-0">
        <Command>
          <CommandInput placeholder="Search Buyer..." />
          <CommandList>
            <CommandEmpty>No framework found.</CommandEmpty>
            <CommandGroup>
              {frameworks.map((framework) => (
                <CommandItem
                  key={framework.value}
                  value={framework.value}
                  onSelect={(currentValue) => {
                    setValue(currentValue === value ? '' : currentValue)
                    setOpen(false)
                  }}
                >
                  <CheckIcon className={cn('mr-2 h-4 w-4', value === framework.value ? 'opacity-100' : 'opacity-0')} />
                  {framework.label}
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  )
}
